### ISSUE TITLE
What do colon at the end of statements ?

### ISSUE THREAD

**Issue by edimitchel** [WebReflection/perseverant#1]
Hello !

Nice project ! But in your code example, I see colon like this : `:Perseverant`.
It's not typescript typing, not a label, not a double colon for binding.. 
What is it ?

Thanks !

**Comment by WebReflection** [comment]
> This is the **meta** description of the API.

https://github.com/WebReflection/perseverant#api

**Comment by WebReflection** [comment]
just to clarify, `method(arg[, optional]):return-type` is what is that meta about, you have every method returning a Promise eventually resolved with a value, and you have the description of needed, and optional arguments.

You can't copy and paste that though, but I don't think it's necessary.

**Comment by edimitchel** [comment]
Ok sorry ! I don't read correctly the title !
